DELETE FROM USERS;

INSERT INTO USERS(NAME, PASSWORD, EMAIL, ROLE)
VALUES ('user', '123', 'user1@mail.ru', 'USER');
INSERT INTO USERS(NAME, PASSWORD, EMAIL, ROLE)
VALUES ('user2', '123', 'user1rere@mail.ru', 'ADMIN');