DELETE FROM USERS;

INSERT INTO USERS(NAME, PASSWORD, EMAIL, ROLE)
VALUES ('user', '$2a$12$ZHKME4W/x8G9RNNDy.hnKe6llXgdGLnDoDxFthnIrGRNxbs4H03a6', 'user1@mail.ru', 'USER');
INSERT INTO USERS(NAME, PASSWORD, EMAIL, ROLE)
VALUES ('user2', '$2a$12$ZHKME4W/x8G9RNNDy.hnKe6llXgdGLnDoDxFthnIrGRNxbs4H03a6', 'user1rere@mail.ru', 'ADMIN');